package com.zhaogang.other.dao.model.nebula_dev;

import java.util.Date;

public class CoreDriverDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.uuid
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.nickname
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.user_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.team_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Integer teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.first_license_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Date firstLicenseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.driving_experience
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Integer drivingExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.license_expired_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Date licenseExpiredDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.gender
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.license_type
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String licenseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.vehicle_group_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Integer vehicleGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.transport_company_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String transportCompanyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.image_url
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.model_version
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String modelVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.employment_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Date employmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.family_member_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String familyMemberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.family_member_phone_number
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String familyMemberPhoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.driver_type
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Boolean driverType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.person_category
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String personCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.identity_card
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.phone_number
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.birthplace
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String birthplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.created_by_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String createdById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.created_by_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.created_time
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.last_modified_by_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String lastModifiedById;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.last_modified_by_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String lastModifiedByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.last_modified_time
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nebula_dev..core_driver.feature_data
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    private String featureData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.id
     *
     * @return the value of nebula_dev..core_driver.id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.id
     *
     * @param id the value for nebula_dev..core_driver.id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.uuid
     *
     * @return the value of nebula_dev..core_driver.uuid
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.uuid
     *
     * @param uuid the value for nebula_dev..core_driver.uuid
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.name
     *
     * @return the value of nebula_dev..core_driver.name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.name
     *
     * @param name the value for nebula_dev..core_driver.name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.nickname
     *
     * @return the value of nebula_dev..core_driver.nickname
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.nickname
     *
     * @param nickname the value for nebula_dev..core_driver.nickname
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.user_id
     *
     * @return the value of nebula_dev..core_driver.user_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.user_id
     *
     * @param userId the value for nebula_dev..core_driver.user_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.team_id
     *
     * @return the value of nebula_dev..core_driver.team_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.team_id
     *
     * @param teamId the value for nebula_dev..core_driver.team_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.first_license_date
     *
     * @return the value of nebula_dev..core_driver.first_license_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Date getFirstLicenseDate() {
        return firstLicenseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.first_license_date
     *
     * @param firstLicenseDate the value for nebula_dev..core_driver.first_license_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setFirstLicenseDate(Date firstLicenseDate) {
        this.firstLicenseDate = firstLicenseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.driving_experience
     *
     * @return the value of nebula_dev..core_driver.driving_experience
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Integer getDrivingExperience() {
        return drivingExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.driving_experience
     *
     * @param drivingExperience the value for nebula_dev..core_driver.driving_experience
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setDrivingExperience(Integer drivingExperience) {
        this.drivingExperience = drivingExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.license_expired_date
     *
     * @return the value of nebula_dev..core_driver.license_expired_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Date getLicenseExpiredDate() {
        return licenseExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.license_expired_date
     *
     * @param licenseExpiredDate the value for nebula_dev..core_driver.license_expired_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setLicenseExpiredDate(Date licenseExpiredDate) {
        this.licenseExpiredDate = licenseExpiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.gender
     *
     * @return the value of nebula_dev..core_driver.gender
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.gender
     *
     * @param gender the value for nebula_dev..core_driver.gender
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.license_type
     *
     * @return the value of nebula_dev..core_driver.license_type
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getLicenseType() {
        return licenseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.license_type
     *
     * @param licenseType the value for nebula_dev..core_driver.license_type
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setLicenseType(String licenseType) {
        this.licenseType = licenseType == null ? null : licenseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.vehicle_group_id
     *
     * @return the value of nebula_dev..core_driver.vehicle_group_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Integer getVehicleGroupId() {
        return vehicleGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.vehicle_group_id
     *
     * @param vehicleGroupId the value for nebula_dev..core_driver.vehicle_group_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setVehicleGroupId(Integer vehicleGroupId) {
        this.vehicleGroupId = vehicleGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.transport_company_id
     *
     * @return the value of nebula_dev..core_driver.transport_company_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getTransportCompanyId() {
        return transportCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.transport_company_id
     *
     * @param transportCompanyId the value for nebula_dev..core_driver.transport_company_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setTransportCompanyId(String transportCompanyId) {
        this.transportCompanyId = transportCompanyId == null ? null : transportCompanyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.image_url
     *
     * @return the value of nebula_dev..core_driver.image_url
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.image_url
     *
     * @param imageUrl the value for nebula_dev..core_driver.image_url
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.model_version
     *
     * @return the value of nebula_dev..core_driver.model_version
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getModelVersion() {
        return modelVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.model_version
     *
     * @param modelVersion the value for nebula_dev..core_driver.model_version
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setModelVersion(String modelVersion) {
        this.modelVersion = modelVersion == null ? null : modelVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.employment_date
     *
     * @return the value of nebula_dev..core_driver.employment_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Date getEmploymentDate() {
        return employmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.employment_date
     *
     * @param employmentDate the value for nebula_dev..core_driver.employment_date
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setEmploymentDate(Date employmentDate) {
        this.employmentDate = employmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.family_member_name
     *
     * @return the value of nebula_dev..core_driver.family_member_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getFamilyMemberName() {
        return familyMemberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.family_member_name
     *
     * @param familyMemberName the value for nebula_dev..core_driver.family_member_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setFamilyMemberName(String familyMemberName) {
        this.familyMemberName = familyMemberName == null ? null : familyMemberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.family_member_phone_number
     *
     * @return the value of nebula_dev..core_driver.family_member_phone_number
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getFamilyMemberPhoneNumber() {
        return familyMemberPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.family_member_phone_number
     *
     * @param familyMemberPhoneNumber the value for nebula_dev..core_driver.family_member_phone_number
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setFamilyMemberPhoneNumber(String familyMemberPhoneNumber) {
        this.familyMemberPhoneNumber = familyMemberPhoneNumber == null ? null : familyMemberPhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.driver_type
     *
     * @return the value of nebula_dev..core_driver.driver_type
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Boolean getDriverType() {
        return driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.driver_type
     *
     * @param driverType the value for nebula_dev..core_driver.driver_type
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setDriverType(Boolean driverType) {
        this.driverType = driverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.person_category
     *
     * @return the value of nebula_dev..core_driver.person_category
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getPersonCategory() {
        return personCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.person_category
     *
     * @param personCategory the value for nebula_dev..core_driver.person_category
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setPersonCategory(String personCategory) {
        this.personCategory = personCategory == null ? null : personCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.identity_card
     *
     * @return the value of nebula_dev..core_driver.identity_card
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.identity_card
     *
     * @param identityCard the value for nebula_dev..core_driver.identity_card
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.phone_number
     *
     * @return the value of nebula_dev..core_driver.phone_number
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.phone_number
     *
     * @param phoneNumber the value for nebula_dev..core_driver.phone_number
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.birthplace
     *
     * @return the value of nebula_dev..core_driver.birthplace
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.birthplace
     *
     * @param birthplace the value for nebula_dev..core_driver.birthplace
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace == null ? null : birthplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.created_by_id
     *
     * @return the value of nebula_dev..core_driver.created_by_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getCreatedById() {
        return createdById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.created_by_id
     *
     * @param createdById the value for nebula_dev..core_driver.created_by_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setCreatedById(String createdById) {
        this.createdById = createdById == null ? null : createdById.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.created_by_name
     *
     * @return the value of nebula_dev..core_driver.created_by_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.created_by_name
     *
     * @param createdByName the value for nebula_dev..core_driver.created_by_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.created_time
     *
     * @return the value of nebula_dev..core_driver.created_time
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.created_time
     *
     * @param createdTime the value for nebula_dev..core_driver.created_time
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.last_modified_by_id
     *
     * @return the value of nebula_dev..core_driver.last_modified_by_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getLastModifiedById() {
        return lastModifiedById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.last_modified_by_id
     *
     * @param lastModifiedById the value for nebula_dev..core_driver.last_modified_by_id
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setLastModifiedById(String lastModifiedById) {
        this.lastModifiedById = lastModifiedById == null ? null : lastModifiedById.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.last_modified_by_name
     *
     * @return the value of nebula_dev..core_driver.last_modified_by_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getLastModifiedByName() {
        return lastModifiedByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.last_modified_by_name
     *
     * @param lastModifiedByName the value for nebula_dev..core_driver.last_modified_by_name
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setLastModifiedByName(String lastModifiedByName) {
        this.lastModifiedByName = lastModifiedByName == null ? null : lastModifiedByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.last_modified_time
     *
     * @return the value of nebula_dev..core_driver.last_modified_time
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.last_modified_time
     *
     * @param lastModifiedTime the value for nebula_dev..core_driver.last_modified_time
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nebula_dev..core_driver.feature_data
     *
     * @return the value of nebula_dev..core_driver.feature_data
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public String getFeatureData() {
        return featureData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nebula_dev..core_driver.feature_data
     *
     * @param featureData the value for nebula_dev..core_driver.feature_data
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    public void setFeatureData(String featureData) {
        this.featureData = featureData == null ? null : featureData.trim();
    }
}