package com.zhaogang.other.dao.mapper.nebula_dev;

import com.zhaogang.other.dao.model.nebula_dev.CoreDriverDO;

public interface CoreDriverDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    int insert(CoreDriverDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    int insertSelective(CoreDriverDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    CoreDriverDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    int updateByPrimaryKeySelective(CoreDriverDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CoreDriverDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nebula_dev..core_driver
     *
     * @mbggenerated Fri Mar 18 12:19:02 CST 2022
     */
    int updateByPrimaryKey(CoreDriverDO record);
}